### ISSUE TITLE
Registration problem

### ISSUE THREAD

**Issue by blendsdk** [myoung34/docker-github-actions-runner#105]
Hi, 

I get the following error, any ideas?

```
worker_1  | Http response code: NotFound from 'POST https://api.github.com/actions/runner-registration'
worker_1  | {"message":"Not Found","documentation_url":"https://docs.github.com/rest"}
worker_1  | Response status code does not indicate success: 404 (Not Found).
worker_1  | .path=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/actions-runner
worker_1  | Starting Runner listener with startup type: service
```

**Comment by myoung34** [comment]
I've not seen this before. What does your configuration look like?

**Comment by blendsdk** [comment]
Hi, I have used the docker-compose config for the organization and replaced the token with my token. In Github I created a runner token for the entire organization.

**Comment by wanieru** [comment]
Hi, I get the exact same problem
```
Attaching to alien-runner_worker_1
worker_1  | Configuring
worker_1  | --------------------------------------------------------------------------------
worker_1  | |        ____ _ _   _   _       _          _        _   _                      |
worker_1  | |       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
worker_1  | |      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
worker_1  | |      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
worker_1  | |       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
worker_1  | |                                                                              |
worker_1  | |                       Self-hosted runner registration                        |
worker_1  | |                                                                              |
worker_1  | --------------------------------------------------------------------------------
worker_1  | # Authentication
worker_1  | Http response code: NotFound from 'POST https://api.github.com/actions/runner-registration'
worker_1  | {"message":"Not Found","documentation_url":"https://docs.github.com/rest"}
worker_1  | Response status code does not indicate success: 404 (Not Found).
worker_1  | .path=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/actions-runner
worker_1  | Starting Runner listener with startup type: service
worker_1  | Started listener process, pid: 65
worker_1  | Started running service
worker_1  | An error occurred: Not configured
worker_1  | Runner listener exited with error code 2
worker_1  | Runner listener exit with retryable error, re-launch runner in 5 seconds.
worker_1  | Starting Runner listener with startup type: service
```

I'm also using Docker-Compose:
```
version: '2.3'

services:
  worker:
    image: myoung34/github-runner:latest
    restart: always
    environment:
      REPO_URL: ${RUNNER_REPO}
      RUNNER_NAME: ${RUNNER_NAME}
      RUNNER_TOKEN: ${RUNNER_TOKEN}
      RUNNER_WORKDIR: /tmp/runner/work
      RUNNER_GROUP: docker-runner
      ORG_RUNNER: 'false'
      LABELS: linux,x64,gpu
    security_opt:
      - label:disable
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/tmp/runner:/tmp/runner'
```

With an .env file like this (I've removed the actual values):
```
RUNNER_REPO=
RUNNER_TOKEN=
RUNNER_NAME=
```

**Comment by myoung34** [comment]
@wanieru make sure you quote the env vars:

I copied yours exactly and got the same error.
I quoted them:

```
services:
  worker:
    image: myoung34/github-runner:latest
    restart: always
    environment:
      REPO_URL: "${RUNNER_REPO}"
      RUNNER_NAME: "${RUNNER_NAME}"
      RUNNER_TOKEN: "${RUNNER_TOKEN}"
      RUNNER_WORKDIR: /tmp/runner/work
      RUNNER_GROUP: docker-runner
      ORG_RUNNER: 'false'
      LABELS: linux,x64,gpu
    security_opt:
      - label:disable
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/tmp/runner:/tmp/runner'
```

and it worked:

```
[myoung:~] 15s % docker-compose up
Recreating myoung_worker_1 ... done
Attaching to myoung_worker_1
worker_1  | Configuring
worker_1  |
worker_1  | --------------------------------------------------------------------------------
worker_1  | |        ____ _ _   _   _       _          _        _   _                      |
worker_1  | |       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
worker_1  | |      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
worker_1  | |      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
worker_1  | |       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
worker_1  | |                                                                              |
worker_1  | |                       Self-hosted runner registration                        |
worker_1  | |                                                                              |
worker_1  | --------------------------------------------------------------------------------
worker_1  |
worker_1  | # Authentication
worker_1  |
worker_1  |
worker_1  | √ Connected to GitHub
worker_1  |
worker_1  | # Runner Registration
worker_1  |
worker_1  |
worker_1  |
worker_1  | √ Runner successfully added
worker_1  | √ Runner connection is good
worker_1  |
```

**Comment by myoung34** [comment]
Didn't mean to hit close.

@blendsdk I can't help you based on that. I need more information about your config.

@wanieru Make sure your token is for the repo, not from the organization. Also try using `docker-compose config` to make sure .env is being injected as expected.

Lastly try using regular docker vs compose to make sure your configuration is right:

```
docker run \
  -e REPO_URL="https://github.com/OctoKode/test1" \
  -e RUNNER_NAME="foo-runner" \
  -e RUNNER_TOKEN="SOMETOKEN" \
  -e RUNNER_WORKDIR="/tmp/runner/work" \
  -e RUNNER_GROUP="docker-runner" \
  -e ORG_RUNNER="false" \
  -e LABELS="linux,x64,gpu" \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /tmp/runner:/tmp/runner \
  myoung34/github-runner:latest
```

**Comment by myoung34** [comment]
I was able to test this working on mine:

```
[myoung:~] % cat docker-compose.yml
services:
  worker:
    image: myoung34/github-runner:latest
    restart: always
    environment:
      REPO_URL: ${RUNNER_REPO}
      RUNNER_NAME: ${RUNNER_NAME}
      RUNNER_TOKEN: ${RUNNER_TOKEN}
      RUNNER_WORKDIR: /tmp/runner/work
      RUNNER_GROUP: docker-runner
      ORG_RUNNER: 'false'
      LABELS: linux,x64,gpu
    security_opt:
      - label:disable
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/tmp/runner:/tmp/runner'
```

```
[myoung:~] 21s % cat .env
RUNNER_REPO=https://github.com/OctoKode/test1
RUNNER_TOKEN=AAGW2MWF6..snip..AOBTZC
RUNNER_NAME=foo
```

```
[myoung:~] % docker-compose up
Recreating myoung_worker_1 ... done
Attaching to myoung_worker_1
worker_1  | Configuring
worker_1  |
worker_1  | --------------------------------------------------------------------------------
worker_1  | |        ____ _ _   _   _       _          _        _   _                      |
worker_1  | |       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
worker_1  | |      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
worker_1  | |      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
worker_1  | |       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
worker_1  | |                                                                              |
worker_1  | |                       Self-hosted runner registration                        |
worker_1  | |                                                                              |
worker_1  | --------------------------------------------------------------------------------
worker_1  |
worker_1  | # Authentication
worker_1  |
worker_1  |
worker_1  | √ Connected to GitHub
worker_1  |
worker_1  | # Runner Registration
worker_1  |
worker_1  |
worker_1  |
worker_1  | √ Runner successfully added
worker_1  | √ Runner connection is good
```
