### ISSUE TITLE
Github/actions: GetError: Can't use 'tar -xzf' extract archive file return code: 2

### ISSUE THREAD

**Issue by bdoublet91** [myoung34/docker-github-actions-runner#113]
Hi,

I use github action with self hosted runners and I don't get problem until now.

```yaml

name: CI mirroring

# Controls when the action will run. 
on:
  push:
  pull_request:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 2 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    timeout-minutes: 15
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:          
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
```

I want to checkout my private github repo to execute action but get error that I haven't before:

```
 Current runner version: '2.278.0'
Runner name: 'runner_1'
Runner group name: 'Default'
Machine name: '2526d86f2a75'
GITHUB_TOKEN Permissions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v2'
Error: Can't use 'tar -xzf' extract archive file: /tmp/runner/_actions/_temp_0207f89a-ccec-4204-a7b6-533817e1094e/cef27ea4-0563-40a2-ac70-c94e38e49e4d.tar.gz. return code: 2.
```

When I use github runner with ubuntu-latest, it's working so I think there is something wrong with my self hosted runner.
I use docker self hosted runner from this project https://github.com/myoung34/docker-github-actions-runner
All working well, runners start, connect to github and get idle state.
When I execute pipeline, runner take the job and execute but get this error. I don't know what change.

I have tar binary and the error means that tar was executed but failed so maybe the download of tar.gz file failed.
```
which tar
/usr/bin/tar
```

Can you help me to debug this ? debug logs, some checks, any idea.

Thanks you

Best regards
