### ISSUE TITLE
Example docker-compose.yml file

### ISSUE THREAD

**Issue by pirate** [myoung34/docker-github-actions-runner#15]
It would be nice to include an example `docker-compose.yml` file:

```yml
version: '2.3'

services:
  worker:
    build: .
    image: myoung34/github-runner:latest
    environment:
      REPO_URL: https://github.com/example/repo
      RUNNER_NAME: example-name
      RUNNER_TOKEN: someGithubTokenHere
      RUNNER_WORKDIR: /home/runner
      ORG_RUNNER: true
      ORG_NAME: example-github-org
      LABELS: linux,x64,gpu
    security_opt:
      - label:disable
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './data/runner:/home/runner'
```

Would something like this be ok? If so, should I PR it?
