### ISSUE TITLE
matrix docker (container) builds fail

### ISSUE THREAD

**Issue by splitice** [myoung34/docker-github-actions-runner#156]
@myoung34 I suspect this is a Github Actions bug. Are you able to confirm (and I'll direct a issue to them accordingly).

```
name: Build
on:
  push:
jobs:
  build:
    runs-on: [self-hosted,linux]
    container: debian:buster
    strategy:
      matrix:
        build:
        - name: debug
        - name: production
[...]
```

Fails to start:
```
  /usr/bin/docker start ce81cdc1a1979d041cd6f5ae1fd5623a9a63ae09c1cac85b897a1f6059b56e07
  Error response from daemon: network github_network_4684e53698f34574a4cc3c670171f70c not found
  Error: failed to start containers: ce81cdc1a1979d041cd6f5ae1fd5623a9a63ae09c1cac85b897a1f6059b56e07
  Error: Docker start fail with exit code 1

```

The strategy of matrix appears to be the issue but I can't see why.

Feedback apreciated.

**Comment by myoung34** [comment]
@splitice it worked for me here: https://github.com/OctoKode/test1/runs/3767512089?check_suite_focus=true

```
name: Test

on: [push]

jobs:
  test:
    runs-on: self-hosted
    strategy:
      matrix:
        build:
        - name: debug
        - name: production
    steps:
    - uses: actions/checkout@v1
    - name: ls
      run: ls -alh; pwd
    - name: verify codegen
      run: ./test.sh
```

**Comment by splitice** [comment]
Try with `container:`

**Comment by myoung34** [comment]
https://github.com/OctoKode/test1/runs/3767922670?check_suite_focus=true

`Error: Container feature is not supported when runner is already running inside container.` which is the limitation of DinD that github doesn't support

Whatever you're running into is on the linux agent not the self-hosted

```
name: Test

on: [push]

jobs:
  test:
    runs-on: self-hosted
    container: debian:buster
    strategy:
      matrix:
        build:
        - name: debug
        - name: production
    steps:
    - uses: actions/checkout@v1
    - name: ls
      run: ls -alh; pwd
    - name: verify codegen
      run: ./test.sh
```

**Comment by splitice** [comment]
Container feature does work with the configuration I provided without the matrix.  In either self hosted or github runner mode. It's only in self-hosed mode with this docker runner that matrix + container fails (I have no data on matrix + container without dind).

This is the error you are chasing (taken from our failing action).

![](https://drive.google.com/uc?id=1Rlkz_Q-ZiolgXxVkdq0Do38g6oaZTOHu)

**Comment by splitice** [comment]
Anyway container works in dind (with all apropriate docker in docker permissions).

Configuration:
```
[...]
jobs:
  build:
    runs-on: [self-hosted,linux]
    container: debian:buster
    steps:
[...]
```

Adding matrix to the configuration does not.

Offtopic FYI DIND nesting also works (Yocto does docker in docker within the job we fire off from Github Actions - in docker). But that's not using GHA containers.

**Comment by myoung34** [comment]
Using

```
name: Test

on: [push]

jobs:
  test:
    runs-on: self-hosted
    container: debian:buster
    strategy:
      matrix:
        build:
        - name: debug
        - name: production
    steps:
    - uses: actions/checkout@v1
    - name: ls
      run: ls -alh; pwd
    - name: verify codegen
      run: ./test.sh
```

fails [as expected](https://github.com/OctoKode/test1/actions/runs/1295312078)

Adding `linux` to `runs-on:` shouldnt make this feature work. I think you might have found an actions bug that should be reported upstream, but this shouldnt work without `linux` in runs-on so I'm not sure what can be done from the self hosted runner side. The runner is working as expected within the DinD limitation

https://github.com/actions/runner/issues/406
https://github.com/actions/runner/issues/367
