### ISSUE TITLE
docker daemon is not running

### ISSUE THREAD

**Issue by saggiyogesh** [myoung34/docker-github-actions-runner#196]
Hi,

I've deployed a runner on Kubernetes v1.21 using the manifest file provided in docs. 
Have also given `privileged` access to this runner pod. 

While it is working fine while using the `docker run` command to start a runner.

```
/usr/bin/docker version
  Client: Docker Engine - Community
   Version:           [20](https://github.com/ss/runs/5846992661?check_suite_focus=true#step:5:20).10.14
   API version:       1.41
   Go version:        go1.16.15
   Git commit:        a[22](https://github.com/ss/runs/5846992661?check_suite_focus=true#step:5:22)4086
   Built:             Thu Mar [24](https://github.com/ss/runs/5846992661?check_suite_focus=true#step:5:24) 01:48:02 2022
   OS/Arch:           linux/amd64
   Context:           default
   Experimental:      true
  Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
  Error: The process '/usr/bin/docker' failed with exit code 1
  ```

**Comment by myoung34** [comment]
Im currently rebuilding my kubernetes set up but have been delayed so I dont have much to offer you for now. I'll circle back though when its rebuilt and running

**Comment by myoung34** [comment]
@saggiyogesh 1.21 uses containerd, no?

Im using 1.22 on k3s:

```
myoung@cluster21:~$ sudo ls /run/k3s/containerd/containerd.sock
/run/k3s/containerd/containerd.sock
```

so here I'd use:

```
      volumes:
        - hostPath:
            path: /run/k3s/containerd/containerd.sock
          name: containerdsocket
      volumeMounts:
        - name: containerdsocket
          mountPath: /var/run/containerd/containerd.sock
```

However it [doesnt look like github runners support containerd](https://github.com/actions/runner/issues/1265)
