### ISSUE TITLE
Introduce an alternative to docker hub, like ghcr.io

### ISSUE THREAD

**Issue by jkroepke** [myoung34/docker-github-actions-runner#244]
The rate-limit issue on dockerhub is still a thing in 2022.

Did you consider to publish your images to Github Container Registry like ghcr.io?

The docker/build-push-action@v2 action is able to push images to multiple registry like:

```yaml
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.ubuntu-${{ matrix.release }}
          pull: true
          push: true
          tags: ${{ env.ORG }}/github-runner:${{ env.TAG }}-ubuntu-${{ matrix.release }},ghcr.io/myoung34/docker-github-actions-runner:${{ env.TAG }}-ubuntu-${{ matrix.release }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
```
