### ISSUE TITLE
nodejs cannot be found when running Docker inside Docker

### ISSUE THREAD

**Issue by JulianGro** [myoung34/docker-github-actions-runner#261]
When trying to use an action that uses nodejs (like action/checkout) inside a Docker container inside the Docker container, it fails with:
```
OCI runtime exec failed: exec failed: unable to start container process: exec: "/__e/node16/bin/node": stat /__e/node16/bin/node: no such file or directory: unknown
```

GitHubs Runners don't have a problem with finding nodejs inside a Docker container, not does the Runner container when used directly.

**Comment by myoung34** [comment]
What is your yaml?

`nodejs (like action/checkout)` doesnt sound like its running in this container. Especially with `/__e/node16/bin/node`, thats definitely not this image.

Example: 

```
➜  ~ docker exec -it 66b5c9b79af8 /bin/bash
root@66b5c9b79af8:/actions-runner# which node
/usr/bin/node

```

**Comment by JulianGro** [comment]
My YAML is pretty huge, so here is a shortened version that would trigger the issue:
```yaml
name: Linux Server CI Build

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  push:
    branches:
      - master

jobs:
  build:
    name: "${{matrix.os}}, ${{matrix.arch}}"
    strategy:
      matrix:
        include:
          - os: fedora-37
            image: docker.io/overte/overte-server-build:0.1.2-fedora-37-aarch64
            arch: aarch64
            runner: linux_aarch64


      fail-fast: false

    runs-on: ${{matrix.runner}}
    container: ${{matrix.image}}

steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
        fetch-depth: 1
```

This will run the workflow inside of a new overte-server-build:0.1.2-fedora-37-aarch64 container instead of the docker-github-actions-runner container directly.
This works fine for GitHub hosted runners, but with docker-github-actions-runner it becomes unable to find node for the actions/checkout step.

Running inside docker-github-actions-runner directly without an additional container doesn't trigger the issue.

Here is a partial explaination on what happens: https://github.com/actions/checkout/issues/334#issuecomment-1241306390
I am not fully understanding what is going on though, and was hoping someone here ran into the same issue.

Interestingly, this only happens with v2 and v3 of the action; v1 doesn't encounter this issue.
The actions/upload-artifact behaves the same way.


Right now I am just avoiding the issue by using the v1 actions and just not doing anything those old versions cannot handle.
