### ISSUE TITLE
Checkout fails in workflow

### ISSUE THREAD

**Issue by skumra** [myoung34/docker-github-actions-runner#279]
Firstly, thank you for sharing this amazing work.

I have set up runners using this implementation and can see the workflow run in these runners. But the workflow fails during the repository checkout step. The workflow runs fine in Github or regular self-hosted runners.

Here is my workflow:
```
jobs:
  clang-format:
    runs-on: self-hosted
    strategy:
      fail-fast: true
    container:
      image: my_image:latest
      options: --user root
      credentials:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
```

Here is the error log:
```
Run actions/checkout@v3
/usr/bin/docker exec  <sha> sh -c "cat /etc/*release | grep ^ID"
OCI runtime exec failed: exec failed: unable to start container process: exec: "/__e/node12/bin/node": stat /__e/node12/bin/node: no such file or directory: unknown
```

Thank you in advance for your help.
