### ISSUE TITLE
install the `Buildx component`

### ISSUE THREAD

**Issue by varu3** [myoung34/docker-github-actions-runner#280]
I get the following error when building an image using Docker Buildx on github-runner. ( `DOCKER_BUIDKIT=1` )

```
ERROR: BuildKit is enabled but the buildx component is missing or broken.
       Install the buildx component to build images with BuildKit:
       https://docs.docker.com/go/buildx/
```

The latest actions-runner image seems to use the v23.0.0 Docker version as shown below.

```
$ docker run -it -v (pwd):/app --entrypoint /bin/bash --rm myoung34/github-runner
root@11027f462c01:/actions-runner# docker -v
Docker version 23.0.0, build e92dd87
```

As shown in the following URL, 
it seems that the docker buildx components needs to be added to use Docker Buildx in v23.0.0 or later.

- https://github.com/docker/cli/blob/master/docs/deprecated.md#legacy-builder-fallback

Could you please install docker buildx components in myoung34/github-runner.

**Comment by myoung34** [comment]
If you can come up with a PR that works across the OS and arch matrix I'm happy to review and help

**Comment by dancernogorsky** [comment]
I hit this same issue. 
After a day of spinning my wheels, I was able to get it working by adding the following to my workflow.

```
- name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
          driver-opts: network=host
          config: .github/buildkit.toml
```

I am using an insecure registry on a private network, so I also had to add the following .github/buildkit.toml

```
[registry.<registryUrl:5000>]
  http = true
  insecure = true
```

Hope this saves someone some time in the future :)
