### ISSUE TITLE
docker/setup-qemu-action@v2  Error: The process '/usr/bin/docker' failed with exit code 1

### ISSUE THREAD

**Issue by aichy126** [myoung34/docker-github-actions-runner#281]
action
```
jobs:
  build:
    runs-on: [self-hosted, linux]
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/amd64,linux/arm64
        version: latest
        endpoint: builders
        driver: docker
```

**to use k3s** 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actions-runner
  namespace: actions-runner-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actions-runner
  template:
    metadata:
      labels:
        app: actions-runner
    spec:
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      - name: workdir
        hostPath:
          path: /tmp/github-runner-xxx
      containers:
      - name: runner
        image: myoung34/github-runner:latest
        env:
        - name: ACCESS_TOKEN
          value: xxxxx
        - name: LABELS
          value: my-label,other-label
        - name: REPO_URL
          value: https://github.com/xxx/xxx
        - name: RUNNER_NAME_PREFIX
          value: actiondev
        - name: RUNNER_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: RUNNER_WORKDIR
          value: /tmp/github-runner-xxx
        volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
        - name: workdir
          mountPath: /tmp/github-runner-xxx
```

to try use 
  @#[196](https://github.com/myoung34/docker-github-actions-runner/issues/196)
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actions-runner
  namespace: actions-runner-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actions-runner
  template:
    metadata:
      labels:
        app: actions-runner
    spec:
      volumes:
      - name: containerdsocket
        hostPath:
          path: /var/run/containerd/containerd.sock
      - name: workdir
        hostPath:
          path: /tmp/github-runner-xxx
      containers:
      - name: runner
        image: myoung34/github-runner:latest
        env:
        - name: ACCESS_TOKEN
          value: xxx
        - name: LABELS
          value: my-label,other-label
        - name: REPO_URL
          value: https://github.com/xxx/xxx
        - name: RUNNER_NAME_PREFIX
          value: actiondev
        - name: RUNNER_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: RUNNER_WORKDIR
          value: /tmp/github-runner-xxx
        volumeMounts:
        - name: containerdsocket
          mountPath: /var/run/containerd/containerd.sock
        - name: workdir
          mountPath: /tmp/github-runner-xxx
```

action jobs

```
Run docker/setup-qemu-action@v2
  with:
    image: tonistiigi/binfmt:latest
    platforms: all
Docker info
  /usr/bin/docker version
  Client: Docker Engine - Community
   Version:           23.0.0
   API version:       [1](https://github.com/aiworklab/actiondev/actions/runs/4105576780/jobs/7082888500#step:3:1).4[2](https://github.com/aiworklab/actiondev/actions/runs/4105576780/jobs/7082888500#step:3:2)
   Go version:        go1.19.5
   Git commit:        e92dd87
   Built:             Wed Feb  1 17:49:08 202[3](https://github.com/aiworklab/actiondev/actions/runs/4105576780/jobs/7082888500#step:3:3)
   OS/Arch:           linux/amd6[4](https://github.com/aiworklab/actiondev/actions/runs/4105576780/jobs/7082888500#step:3:4)
   Context:           default
  Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Error: The process '/usr/bin/docker' failed with exit code 1
```
The problem has been solved.
![image](https://user-images.githubusercontent.com/16996097/217155302-bb600410-814f-4b67-a45a-3df91f162ac8.png)

autok3s need  Volume docker docker.sock
```
/var/run/docker.sock:/var/run/docker.sock:ro
```
