### ISSUE TITLE
Worker fails with: /bin/bash: /_work/Local: No such file or directory

### ISSUE THREAD

**Issue by Shynixn** [myoung34/docker-github-actions-runner#283]
Hello, thank you for your docker images. I have used this runner successfully for months now. However, after updating to the latest image today, all of my workflows fail with the message ``/bin/bash: /_work/Local: No such file or directory``. 

It seems like the commands try to get executed in ``/_work/Local`` instead of ``/_work/Local Runner``.
Do you know how I can fix that?

Error:
```bash
Run ls   
  ls   
  shell: /bin/bash -e {0}
/bin/bash: /_work/Local: No such file or directory
Error: Process completed with exit code 1.
```

My workflow file:

```yaml
name: MyWorkflow

on:
  workflow_dispatch:

jobs:
  build:
    defaults:
      run:
        working-directory: "MyProgram"
    runs-on: raspberry_pi

    steps:
    - uses: actions/checkout@v3
    
    - name: Do some stuff
      run: |
        ls   
```

Docker-compose file:

```yaml
version: "3.9"

services:
  github-worker:
    image: myoung34/github-runner:ubuntu-bionic
    restart: "always"
    environment:
      REPO_URL: https://github.com/nope/nope
      RUNNER_NAME: "Local Runner"
      LABELS: "raspberry_pi"
      ACCESS_TOKEN: nope
      DISABLE_AUTO_UPDATE: true
    security_opt:
      # needed on SELinux systems to allow docker container to manage other docker containers
      - label:disable
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/tmp/runner:/tmp/runner'
```
