### ISSUE TITLE
Unable to access KVM kernel module when running QEMU-KVM

### ISSUE THREAD

**Issue by fabifont** [myoung34/docker-github-actions-runner#303]
Hello,
I'm currently self-hosting a GitHub Runner using your docker-compose variant. I am attempting to create a workflow to test a program within a QEMU-KVM image.

However, I've run into an issue that's preventing the execution of the `qemu-system-x86_64` command. The error message I'm receiving is `Could not access KVM kernel module: No such file or directory`.

Here is the relevant part of my workflow:

```yaml
    - name: Setup KVM
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-system-x86 qemu-kvm libvirt-daemon-system libvirt-daemon libvirt-clients bridge-utils qemu virtinst udev
        sudo adduser `id -un` kvm
        sudo adduser `id -un` libvirt

    - name: Download Arch Linux ISO
      run: |
        if [[ ! -f "arch.iso" ]] || [[ "$(find arch.iso -mtime +7)" ]]; then
          curl -v -sSL0 -C - -o arch.iso https://archmirror.it/repos/iso/latest/archlinux-x86_64.iso
        fi

    - name: Create Arch Linux VM image
      run: rm -f arch.qcow2 && qemu-img create -f qcow2 arch.qcow2 8G

    - name: Boot Arch Linux VM 
      run: |
        qemu-system-x86_64 \
          -enable-kvm \
          -cdrom arch.iso \
          -boot d \
          -m 2G \
          -hda arch.qcow2 \
          -net user,hostfwd=tcp::2222-:22 \
          -net nic \
          -display none \
          -nographic \
          -no-reboot \
          -vga none \
          -global isa-debugcon.iobase=0x402 \
          -debugcon file:logfile.log \
          -kernel linux \
          -initrd initramfs-linux.img \
          -append "console=ttyS0,115200n8 serial"
```

Could you provide some guidance on how to enable the usage of KVM within the Runner environment? Any assistance would be greatly appreciated.

**Comment by myoung34** [comment]
I'm not sure honestly. If I had to guess either the module isnt loaded or virtualization isnt enabled, but this is a bit outside the scope of the docker runner itself

**Comment by fabifont** [comment]
I've managed to resolve the problem by creating a custom image with qemu-kvm and dependencies, as well as updating the docker-compose.yaml file.

Here is the Dockerfile:
```dockerfile
FROM myoung34/github-runner:latest

# Update packages and install qemu-kvm and dependencies
RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
```

And here is the updated docker-compose.yaml:
```yaml
version: "3.9"

services:
  my-worker:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    devices:
      - "/dev/kvm:/dev/kvm"
    environment:
      REPO_URL: https://github.com/my-user/my-repo
      RUNNER_NAME: my-runner
      RUNNER_TOKEN: ${RUNNER_TOKEN}
      RUNNER_WORKDIR: /tmp/runner/work
      RUNNER_SCOPE: "repo"
      LABELS: linux,x64,gpu
    security_opt:
      # needed on SELinux systems to allow docker container to manage other docker containers
      - label:disable
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/tmp/my-runner:/tmp/runner"
      # note: a quirk of docker-in-docker is that this path
      # needs to be the same path on host and inside the container,
      # docker mgmt cmds run outside of docker but expect the paths from within
```

Please note that while this solution worked in this particular instance, it may not be the most optimal depending on the specifics of your setup and needs.
