### ISSUE TITLE
Cannot connect to the Docker daemon

### ISSUE THREAD

**Issue by carmilso** [myoung34/docker-github-actions-runner#314]
Hi!

I'm trying to run docker-in-docker with the actions runner image in Kubernetes v1.21, so I have defined this deployment yaml:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actions-runner
  namespace: common
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actions-runner
  template:
    metadata:
      labels:
        app: actions-runner
    spec:
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      - name: workdir
        hostPath:
          path: /tmp/github-runner-your-repo
      containers:
      - name: runner
        image: myoung34/github-runner:latest
        env:
        - name: ACCESS_TOKEN
          value: XXX
        - name: RUNNER_SCOPE
          value: "repo"
        - name: REPO_URL
          value: XXX
        - name: RUNNER_NAME_PREFIX
          value: foo
        - name: RUNNER_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: RUNNER_WORKDIR
          value: /tmp/github-runner-your-repo
        volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
        - name: workdir
          mountPath: /tmp/github-runner-your-repo
```

When I do a kubectl exec to the pod that is running, I try to start the docker service, so I run `service docker start` and it tells me that docker is starting: `* Starting Docker: docker` but that never happens.

So next time I try to do a `docker ps` it says: `Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

What I am doing wrong? I need to be able to run docker inside this pod.
