### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by basz** [myoung34/docker-github-actions-runner#322]
Hi,

I run these in a `docker compose` way on several repositories. I regularly encounter jobs failing due to; 

No space left on device : '/actions-runner/_diag/Worker_20230918-091841-utc.log'

When this happens I need to delete the container and start over. After some time it happens again.

I don't understand this because i have EPHEMERAL set to true and I would assume the container is reset. 

docker-compose.yaml
```yml 
runner-plhw:
        image: 'myoung34/github-runner:ubuntu-jammy'
        deploy:
          replicas: 2
        # command: config.cmd remove
        environment:
            - ACCESS_TOKEN=${GITHUB_TOKEN}
            - EPHEMERAL=true
            - RUNNER_NAME_PREFIX=plhw
            - RUNNER_SCOPE=org
            - DISABLE_AUTO_UPDATE=true
            - ORG_NAME=plhw
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
        restart: always
```

Looking at that log file I got the idea that mayby the '/_work/' directory should be mounted to a host directory. I have enough space. Would that solve it? Is that safe to do?

edit: tried to do a bind mount to /_work. that didn't work. permission denied errors for executables.

edit2: I am guessing point three of https://github.com/myoung34/docker-github-actions-runner/wiki/Usage#ephemeral-runners isn't achievable with `docker compose up -d`. Containers are restarted but not deleted when finished.
