### ISSUE TITLE
Use modern socket in Kubernetes YAML sample

### ISSUE THREAD

**Issue by jrbe228** [myoung34/docker-github-actions-runner#325]
The sample K8s [YAML](https://github.com/myoung34/docker-github-actions-runner/wiki/Usage#kubernetes) mounts dockerd socket by default. Modern K8s has [deprecated](https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/) dockerd as a runtime since v1.20. Any users of this repo (such as me) on AKS/EKS/GKE would find the sample YAML failing. I recommend defaulting to containerd, as the inline comments mention. Only the `path:` and `mountPath` lines would need to change: 
```
      ...
      volumes:
      - name: dockersock
        hostPath:
          path: /run/containerd/containerd.sock  # containerd socket

      containers:
      - name: runner
        ...
        volumeMounts:
        - name: dockersock
          mountPath: /run/containerd/containerd.sock # containerd socket
        ...
```
