### ISSUE TITLE
Extremely slow?

### ISSUE THREAD

**Issue by ckocyigit** [myoung34/docker-github-actions-runner#327]
Hello all,

I'm running this runner on my server platform and experiencing astronomically high waiting times on my actions.

A simple npm install command runs appr. 1h. 

Locally it takes about 30 seconds. Why is it taking so long on the runner?

Current configuration:

```
version: '3.8'
services:
  worker:
    image: myoung34/github-runner:latest
    environment:
      ACCESS_TOKEN: ${ACCESS_TOKEN}
      RUNNER_NAME: ${RUNNER_NAME}
      RUNNER_SCOPE: ${RUNNER_SCOPE}
      ORG_NAME: ${ORG_NAME}
      EPHEMERAL: ${EPHEMERAL}
      START_DOCKER_SERVICE: ${START_DOCKER_SERVICE}
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
```

It's an organization runner. EPHEMERAL is set to true.

I have tried increasing ulimits, experimented with START_DOCKER_SERVICE and also tried mounting /tmp/runner

Nothing helped unfortunately :(
