### ISSUE TITLE
Runners are not deregistered

### ISSUE THREAD

**Issue by 1cedsoda** [myoung34/docker-github-actions-runner#352]
I deploy 6 runners at a time with docker swarm. Offline runners are not deregistered and stay forever in the GitHub overview. Now I have hit the limit of 10000 registered runners and new runner's won't start due to a runner group limit.

<img width="840" alt="image" src="https://github.com/myoung34/docker-github-actions-runner/assets/29167146/1bc2c882-4352-4354-a02e-d5c7f2d1838e">

This is my docker compose which I deploy as a docker stack (swarm).

```yml
version: "3.3"
services:
  runner:
    image: myoung34/github-runner:latest
    environment:
      RUNNER_SCOPE: org
      ACCESS_TOKEN: github_pat_xxxxxxxxxxxxxxxxxxxxxx
      ORG_NAME: myorgxxx
      LABELS: vps-bucket
      RUNNER_NAME_PREFIX: vps-bucket
    deploy:
      replicas: 3
    security_opt:
      # needed on SELinux systems to allow docker container to manage other docker containers
      - label:disable
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/runner:/tmp/runner"
      - "/root/dockervolumes:/root/dockervolumes"
```

This is the output if a runner tries to start:

```
Runner reusage is disabled
Obtaining the token of the runner
Configuring
--------------------------------------------------------------------------------
|        ____ _ _   _   _       _          _        _   _                      |
|       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
|      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
|      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
|       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
|                                                                              |
|                       Self-hosted runner registration                        |
|                                                                              |
--------------------------------------------------------------------------------
# Authentication
√ Connected to GitHub
# Runner Registration
Runner group 1 has reached max limit of 10000 runners.
An error occurred: Not configured. Run config.(sh/cmd) to configure the runner.
```

How can I reuse a runner for multiple jobs?

How can I remove the runners automatically? I read about the `--ephermeral` mode. Can I just add it by overriding the command like this: `command: ["./bin/Runner.Listener", "run", "--startuptype", "service", "--ephermeral"]`.
