### ISSUE TITLE
Possible container networking issue

### ISSUE THREAD

**Issue by SubtypeZero** [myoung34/docker-github-actions-runner#396]
To sum it up, what I have is an Ubuntu Server installation with Docker installed on it and I'm running a docker [registry](https://hub.docker.com/_/registry) and this GitHub Actions runner on the same machine, both using the same Docker network.

The runner appears to be functioning correctly and I'm able to `docker login localhost:5000` to the registry from the host machine. I can also connect through a Traefik reverse proxy by changing my hosts file to have some subdomain point to it and it all works fine.

Using both of those approaches to log into the registry, I have been able to do the following successfully:
```
docker pull hello-world
docker tag hello-world localhost:5000/hello-world:latest
docker push localhost:5000/hello-world:latest
```
And upon checking the command output and the filesystem for the registry, I can see that both approaches work just fine.

Figuring this should work in GitHub Actions, my next step was to set up a job like this:
```
name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  REGISTRY: localhost:5000
  IMAGE_NAME: ${{ github.event.repository.name }}

jobs:
  build-push:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Log into Docker registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
```

Just for fun, here's what part of the docker-compose file looks like:
```
services:
  registry:
    image: registry:2
    container_name: registry
    restart: always
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./registry:/var/lib/registry
      - ./registry-auth:/auth
    ports:
      - "5000:5000"
    environment:
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/.htpasswd
    labels:
      - traefik.enable=true
      - traefik.http.routers.registry.entrypoints.websecure
      - traefik.http.routers.registry.rule=Host(`registry.${HOST_NAME}`)
      - traefik.http.routers.registry.tls=true
      - traefik.http.routers.registry.service=registry
      - traefik.http.services.registry.loadbalancer.server.port=5000
    networks:
      - proxy

  runner:
    image: myoung34/github-runner:latest
    container_name: runner
    restart: always
    security_opt:
      - no-new-privileges:true
    environment:
      - RUNNER_NAME_PREFIX=${GITHUB_RUNNER_NAME_PREFIX}
      - ACCESS_TOKEN=${GITHUB_ORG_ACCESS_TOKEN}
      - RUNNER_WORKDIR=/tmp/github-runner
      - RUNNER_GROUP=Default
      - RUNNER_SCOPE=org
      - DISABLE_AUTO_UPDATE=true
      - ORG_NAME=${GITHUB_ORG_NAME}
      - LABELS=self-hosted,linux,docker
    volumes:
      - ./runner-work:/tmp/github-runner
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
```

It looks about right and it almost works, however... the final step of actually pushing the image to the repository doesn't seem to work, so I suspect there may be some sort of networking issue going on that I haven't had any luck figuring out after many attempts and many hours invested.

Upon looking at the GitHub Action logs, I can see the `docker login` step succeeding:
```
Run docker/login-action@v3
Logging into localhost:5000...
Login Succeeded!
```

And the push step unfortunately failing with the same repository link:
```
Error: buildx failed with: ERROR: failed to solve: failed to push localhost:5000/my-app:latest: failed to do request: Head "http://localhost:5000/v2/my-app/blobs/sha256:<HASH>": dial tcp [::1]:5000: connect: connection refused
```

I've also tried dumping the cached docker login credentials to make sure they are actually there and that it's not giving me a false positive. The credentials were there as I would expect, but this makes me further question why the image failed to push. If it was able to connect to the registry to log in, then why can't it connect to the registry again when trying to push the image?

Maintainers familiar with this repo may know more than I about why this is happening, though one of my suspicions is that maybe as new containers are being created they might not be getting put on the same docker network as the others or they can't access the host network so they can't reach the registry. I'm not entirely sure, but hopefully someone is able to catch something I'm missing here or point me toward a solution to this problem I'm facing.

**Comment by myoung34** [comment]
This is outside the scope of the runner here. The containers are essentially just basic debian/ubuntu containers with added software. There's no networking changes or configuration in any way, so without more troubleshooting on your side to prove it, this is a red herring and likely something client-side related to how your containers talk to each other. They have no issues building and pushing images to repositories such as ghcr and docker hub.

I'll let this issue linger for others for a period of time, but there is no reason to suspect the runners are built in a way to cause this.

**Comment by SubtypeZero** [comment]
I realize it may sound strange, but what I'm trying to do is give the runner (and any other containers it may create temporarily) the ability to connect to other containers on the host machine that they share.

I have tried localhost, I've tried container names, and I've even tried modifying the hosts file on the machine to point an "external domain" back to localhost and use that. All of those approaches seem to work on the host machine itself, they mostly seem to work (with the right ports, etc.) from the runner during the docker login step, but it always fails to push and it's always some sort of networking issue.

I would like some help getting runner steps in a position where they are consistently able to connect to other containers running on the same machine.

**Comment by SubtypeZero** [comment]
This is possibly related, I adjusted the workflow to use different registry urls that should in theory point to the same place but allow me to differentiate the login attempts in the registry container logs. I'm seeing login failures for both hosts even though the action claims the docker login was successful.

https://github.com/docker/for-linux/issues/802

**Comment by SubtypeZero** [comment]
It seems I'm back where I started. I did some more troubleshooting and attempted to use the generated htpasswd file along with the corresponding user/password the registry makes for you if you don't specify one. That didn't work either, so I tried disabling authentication for the registry altogether, verified the docker login step actually worked, and the docker/build-push-action step still failed. It's not resolving things at all with the hosts file and it seems to be using public dns so that step can't connect to the registry container. I also tried using localhost and the registry container name as the host but neither of those worked, as I suspected would be the case.

**Comment by SubtypeZero** [comment]
The plot thickens... I found this when trying to dive deeper into the problem: https://github.com/docker/buildx/issues/175
But that also leads me to this interesting approach, which I'm about to try: https://github.com/Hronom/buildx-add-host-example

**Comment by SubtypeZero** [comment]
My conclusion is that the `docker/build-push-action` and/or `docker/buildx` do not appear to support my use-case of building and pushing to a local registry running on the same host as a self-hosted GitHub Actions runner. A tried a lot of different things and none of them worked for various reasons.

In the end, my solution is to simply not use those actions:
```
name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  REGISTRY: localhost:5000
  IMAGE_NAME: ${{ github.event.repository.name }}

jobs:
  build-push:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:latest .

      - name: Tag Docker Image for Local Registry
        run: |
          docker tag ${{ env.IMAGE_NAME }}:latest ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Log into Docker Registry
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ env.REGISTRY }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Push Docker Image to Local Registry
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
```

When building and pushing with only the basic commands everything works just fine and the image is successfully pushed to the local repository.
