### ISSUE TITLE
Wrong binaries for ARM architecture in docker image

### ISSUE THREAD

**Issue by Pentusha** [myoung34/docker-github-actions-runner#4]
On my Raspberry PI 4
```bash
pentusha@pc0:~ $ arch; docker run -it myoung34/github-runner:latest /actions-runner/bin/Runner.Listener
armv7l
ldd: ./bin/libcoreclr.so: No such file or directory
ldd: ./bin/System.Security.Cryptography.Native.OpenSsl.so: No such file or directory
ldd: ./bin/System.IO.Compression.Native.so: No such file or directory
/actions-runner/config.sh: line 78: ./bin/Runner.Listener: cannot execute binary file: Exec format error
/actions-runner/run.sh: line 27: /actions-runner/bin/Runner.Listener: cannot execute binary file: Exec format error
```

On my x86-64 pc works well
```bash
arch; docker run -it myoung34/github-runner:latest /actions-runner/bin/Runner.Listener
x86_64
ldd: ./bin/libcoreclr.so: No such file or directory
ldd: ./bin/System.Security.Cryptography.Native.OpenSsl.so: No such file or directory
ldd: ./bin/System.IO.Compression.Native.so: No such file or directory

--------------------------------------------------------------------------------
|        ____ _ _   _   _       _          _        _   _                      |
|       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
|      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
|      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
|       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
|                                                                              |
|                       Self-hosted runner registration                        |
|                                                                              |
--------------------------------------------------------------------------------

# Authentication

What is the URL of your repository? Exiting...
An error occurred: Not configured
```
Pretty sure that ACTIONS_ARCH not respected and it is always x64.

**Comment by myoung34** [comment]
Fixed with #5

**Comment by Pentusha** [comment]
Confirm. Now runners works on my raspberry pi cluster.
BTW, kubernetes deployment

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actions-runner
  namespace: runners
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actions-runner
  template:
    metadata:
      labels:
        app: actions-runner
    spec:
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      containers:
      - name: runner
        image: myoung34/github-runner:latest
        env:
        - name: RUNNER_TOKEN
          value: AARGHTHISISYOURGHACTIONSTOKEN
        - name: REPO_URL
          value: https://github.com/your-account/your-repo
        volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
```
