### ISSUE TITLE
It is possible to run docker daemon in a Github Self hosted runner?

### ISSUE THREAD

**Issue by marcelmedeiros1** [myoung34/docker-github-actions-runner#406]
I'm trying to configure my github self-hosted runner, but there is two main issues that i'm facing: The docker daemon not running and npm not found (I already tried to use a image that installs npm). Can you help me?

**Comment by myoung34** [comment]
The best I can do is make sure you set `START_DOCKER_SERVICE` 

Npm can be installed with a PR, some notes are here: https://github.com/myoung34/docker-github-actions-runner/issues/405

**Comment by marcelmedeiros1** [comment]
That's not working for me.. Can you test running the `'gruntwork-io/terragrunt-action@v2'` and `'creyD/prettier_action@v4.3'` in a Self Hosted runner? 

The first one says that the Docker is not running and the second doesn't recognize npm commands

**Comment by Kamilcuk** [comment]
Hi @marcelmedeiros1 I tested the following:

```
  tester1:
    runs-on: nomadtools
    steps:
      - uses: gruntwork-io/terragrunt-action@v2
  tester2:
    runs-on: nomadtools
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: creyD/prettier_action@v4.3
```

on "myoung34/github-runner:latest" with START_DOCKER_SERVICE="true" and --privileged. The `gruntwork-io/terragrunt-action@v2` built fine and complained about `One of tf_version or tofu_version must be set` and `creyD/prettier_action@v4.3` complained about `No files matching the pattern were found: "**/*.js".`, so both run fine and these errors are expected. https://github.com/Kamilcuk/runnertest/actions/runs/11426600049/job/31789711472

So check your configuration and check your logs. Npm is not installed, which is great, because the base image is minimal. To preinstall the stuff that you want, docker build your own Dockerfile with the stuff you want to have.
