### ISSUE TITLE
Stuck at authentication on Linux ARM64 server while working fine on Windows

### ISSUE THREAD

**Issue by HeilOliver** [myoung34/docker-github-actions-runner#420]
I have the following Docker Run command

`docker run -d --name "github-runner" -e RUNNER_SCOPE="org" -e ORG_NAME="my-org" -e ACCESS_TOKEN="ghp_***" -e RUNNER_NAME="org-runner" -e LABELS="arm64" -e RUNNER_WORKDIR="/_work" -e EPHEMERAL="true" ghcr.io/myoung34/docker-github-actions-runner:latest`

On my Windows 11 machine, the runner starts without a problem and I can do stuff with it. However, on our Linux arm64 server, it gets stuck in authentication step forever without any message. 

```
Runner reusage is disabled
Obtaining the token of the runner
Ephemeral option is enabled
Configuring

--------------------------------------------------------------------------------
** ASCII ART **
--------------------------------------------------------------------------------

# Authentication
```

When I add the two env flags `DEBUG_ONLY` and `DEBUG_OUTPUT`, I get this output and the container exited after that:

```
Runner reusage is disabled
Disable automatic registration: false
Random runner suffix: true
Runner name: org-runner
Runner workdir: /_work
Labels: arm64
Runner Group: Default
Github Host: github.com
Run as root:true
Start docker: false
Running ./bin/Runner.Listener run --startuptype service
```

The server is a Hetzner vServer behind a firewall. When I bashed in the container I can ping and curl github without any problem so this shouldn't be the problem. 
Can anyone tell me what I am missing here?

**Comment by myoung34** [comment]
It has to be a network issue. 

I can't recreate it. My runner is running on [arm64](https://github.com/myoung34/homelab/blob/main/k8s/prod/actions-runner/actions.yaml#L46)

```
Runner reusage is disabled
Obtaining the token of the runner
Configuring
--------------------------------------------------------------------------------
|        ____ _ _   _   _       _          _        _   _                      |
|       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
|      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
|      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
|       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
|                                                                              |
|                       Self-hosted runner registration                        |
|                                                                              |
--------------------------------------------------------------------------------
# Authentication
√ Connected to GitHub
# Runner Registration
√ Runner successfully added
√ Runner connection is good
# Runner settings
√ Settings Saved.
√ Connected to GitHub
Current runner version: '2.321.0'
2024-12-20 01:01:53Z: Listening for Jobs
```

**Comment by lava83** [comment]
I have the same issue with an **cax21** on hetzner behind software firewall and in a private network. If I start a runner with `./run.sh` - the runner is working fine. 

My `docker-compose.yml` : 

```
services:
  waz-github-runner:
    restart: always
    image: myoung34/github-runner:latest
    environment:
      RUNNER_SCOPE: org
      ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
      ORG_NAME: Werksarztzentrum-Deutschland-GmbH
      LABELS: waz-github-runner
      RUNNER_NAME_PREFIX: waz-github-runner
      EPHEMERAL: true
    deploy:
      replicas: ${RUNNER_REPLICAS}
    security_opt:
      - label:disable
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
```

On my Mac the compose file works fine. 

Do we have to release special ports?
