### ISSUE TITLE
New Org Runner Not Picking Up Jobs

### ISSUE THREAD

**Issue by smashedr** [myoung34/docker-github-actions-runner#428]
I setup a new runner for an org using token authentication. The runner registers, connects, and is Idle waiting for jobs, but never picks up any jobs. 

The runner shows online:

![Image](https://github.com/user-attachments/assets/f35a1191-2040-4a69-8a89-22e1ff494fb8)

But all the jobs sit idle.

```text
Requested labels: self-hosted
...
Waiting for a runner to pick up this job...
```

With nothing in the logs:

```
Runner reusage is disabled
Obtaining the token of the runner
Configuring
--------------------------------------------------------------------------------
|        ____ _ _   _   _       _          _        _   _                      |
|       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
|      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
|      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
|       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
|                                                                              |
|                       Self-hosted runner registration                        |
|                                                                              |
--------------------------------------------------------------------------------
# Authentication
√ Connected to GitHub
# Runner Registration
√ Runner successfully added
√ Runner connection is good
# Runner settings
√ Settings Saved.
Disable automatic registration: false
Random runner suffix: true
Runner name: swarm-aarch64
Runner workdir: /_work
Labels: default
Runner Group: Default
Github Host: github.com
Run as root:true
Start docker: false
Running ./bin/Runner.Listener run --startuptype service
√ Connected to GitHub
Current runner version: '2.322.0'
2025-02-28 08:29:03Z: Listening for Jobs
```

Compose file:

```yaml
version: "3.8"

services:
  actions-runner:
    image: myoung34/github-runner:latest
    restart: always
    environment:
      RUNNER_NAME: swarm-aarch64
      RUNNER_SCOPE: org
      ORG_NAME: cssnr
      ACCESS_TOKEN: "${GH_PAT}"
      RUNNER_WORKDIR: /_work
      #LABELS: swarm-aarch64
      #RUNNER_GROUP: my-group
      DEBUG_OUTPUT: "true"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2.0"
          memory: 500M
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/docker/actions-runners:/_work
```

Token Permissions:

![Image](https://github.com/user-attachments/assets/f98969fb-1223-4346-8090-bbbf1c5c5446)

I have this setup on another org, using App authentication and it works just fine. I just can't get token auth to work with an org. 

EDIT:

I have noticed when I go to the Runners section in one of my org's repositories, the runner does not show up there. But does show up in the org as shown above. So there seems to be a disconnect somewhere because the one I setup with App Authentication does shows up int he org, and here...

![Image](https://github.com/user-attachments/assets/5a7e428e-36ae-4354-aefd-da906e0c391c)

Reference Issue Repository/Org: https://github.com/cssnr/django5-boiler/actions/runners?tab=self-hosted

Reference App Auth Org (working): https://github.com/django-files/django-files/actions/runners?tab=self-hosted
