### ISSUE TITLE
Repo-Runner: Invalid configuration provided for token (PAT)

### ISSUE THREAD

**Issue by maxstreifeneder** [myoung34/docker-github-actions-runner#80]
Hey,

first of all: thank you so much for your work! 

I'm trying to self-host a repo runner. Works with the RUNNER_TOKEN but whatever PAT I provide I get the following error: 

```bash: 
worker_1  | # Authentication
worker_1  | 
worker_1  | Invalid configuration provided for token. Terminating unattended configuration.
worker_1  | .path=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/actions-runner
worker_1  | Starting Runner listener with startup type: service
worker_1  | Started listener process
worker_1  | Started running service
worker_1  | An error occurred: Not configured
worker_1  | Runner listener exited with error code 2
worker_1  | Runner listener exit with retryable error, re-launch runner in 5 seconds.
```

docker-compose.yml with RUNNER_TOKEN:
```yml
version: '3.7'

services:
  worker:
    image: myoung34/github-runner:latest
    environment:
      REPO_URL: https://my.enterprise.github/reponame
      RUNNER_NAME: example-name
      RUNNER_TOKEN: AAABSK3BWNOIMZ7BBJM55WDABxxxx
      RUNNER_WORKDIR: /tmp/runner/work
      RUNNER_GROUP: my-group
      ORG_RUNNER: 'false'
      LABELS: linux,x64,gpu
    security_opt:
      # needed on SELinux systems to allow docker container to manage other docker containers
      - label:disable
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/tmp/runner:/tmp/runner'
      # note: a quirk of docker-in-docker is that this path
      # needs to be the same path on host and inside the container,
      # docker mgmt cmds run outside of docker but expect the paths from within
```

docker-compose.yml for PAT:

```yml
version: '3.7'

services:
  worker:
    image: myoung34/github-runner:latest
    environment:
      REPO_URL: https://my.enterprise.github/reponame
      RUNNER_NAME: example-name-pat
      ACCESS_TOKEN: e9f1378648e4f677aa2c5b0a5130f6fce523xxxx
      RUNNER_WORKDIR: /tmp/runner/work
      RUNNER_GROUP: my-group
      ORG_RUNNER: 'false'
      LABELS: linux,x64,gpu
    security_opt:
      # needed on SELinux systems to allow docker container to manage other docker containers
      - label:disable
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/tmp/runner:/tmp/runner'
      # note: a quirk of docker-in-docker is that this path
      # needs to be the same path on host and inside the container,
      # docker mgmt cmds run outside of docker but expect the paths from within
```

I provided all OAuth scopes for the PAT: 

![image](https://user-images.githubusercontent.com/36535298/105573162-e4628100-5d5b-11eb-9a1c-0bc9fcd0cae3.png)

While I'm writing this - I might have found the issue. Our API endpoint is: 
https://my.enterprise.github/api/v3 - as far as I have understood your token.sh script always uses api.github.com, right? 

Could that be the issue? Is there any way to configure the API endpoint (optional parameter)? :)

Cheers and thanks in advance,
Max
