### ISSUE TITLE
What is the recommended way to modify the myoung34/github-runner:latest image?

### ISSUE THREAD

**Issue by Tjitse-E** [myoung34/docker-github-actions-runner#83]
I'm using docker-compose to run the `myoung34/github-runner:latest` image. It works great, thanks a lot!

Now I need some extre dependencies. For example, I want to execute:
```
sudo apt-get install joe
```

What is the best way to achieve this? I could ofcourse clone this repository, edit the Dockerfile/entrypoint.sh and build my own image, but is there a better (cleaner) way?

**Comment by damacus** [comment]
We use it as a base image, so:

```docker
FROM myoung34/github-runner:<VERSION>

apt update \
apt install vim
```

**Comment by Tjitse-E** [comment]
@damacus thanks! This is what i'm looking for.

Final result, in case anyone has the same question:

docker-compose.yml
```
version: '3.9'

services:
  runner:
    build:
      context: .
      dockerfile: "Dockerfile-Runner"
    environment:
      - RUNNER_NAME_PREFIX=${RUNNER_NAME_PREFIX}
      - ORG_RUNNER=${ORG_RUNNER}
      - LABELS=${SERVER}
      - ORG_NAME=${ORG_NAME}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
    restart: 'unless-stopped'
    volumes:
      - '/tmp/runner:/tmp/runner'
```

Dockerfile-Runner
```
FROM myoung34/github-runner:2.277.1

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y your-packages
```
