### ISSUE TITLE
Network issue with docker on AWS EKS

### ISSUE THREAD

**Issue by phoenix-zhu** [myoung34/docker-github-actions-runner#97]
Hey myoung34,

Thanks for making this image, I run into a network issue while using this image on AWS EKS cluster.

Here is my deployment config, copied from readme.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actions-runner
  namespace: github
spec:
  replicas: 2
  selector:
    matchLabels:
      app: actions-runner
  template:
    metadata:
      labels:
        app: actions-runner
    spec:
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      - name: workdir
        hostPath:
          path: /tmp/github-runner
      containers:
      - name: runner
        image: myoung34/github-runner:latest
        imagePullPolicy: Always
        env:
        - name: ORG_RUNNER
          value: "true"
        - name: ORG_NAME
          value: myorg
        - name: LABELS
          value: test
        - name: RUNNER_TOKEN
          valueFrom:
            secretKeyRef:
              key: RUNNER_TOKEN
              name: actions-runner
        - name: REPO_URL
          value: https://github.com/myorg
        - name: RUNNER_NAME_PREFIX
          value: test
        - name: RUNNER_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: RUNNER_WORKDIR
          value: /tmp/github-runner
        - name: RUNNER_GROUP
          value: test
        volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
        - name: workdir
          mountPath: /tmp/github-runner
```

While I run docker on the runner, the containers couldn't access the internet. I log into the pod and run a docker image, there isn't any network in that container. I tried the same thing on my laptop, everything was good, not really sure the reason. Setting the `-net=host` with docker command is a workaround but ugly. I was wondering whether there is a better solution for this? 

Hope these screenshots would help you understand.

On my Laptop
![image](https://user-images.githubusercontent.com/12430884/112012106-dd8d9a00-8b63-11eb-82d5-3436fbdb739a.png)

On EKS
![image](https://user-images.githubusercontent.com/12430884/112013196-d2873980-8b64-11eb-944d-34253ffefcfe.png)

Zhu Ye
